# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.0-preview5-19227-01'

- script: dotnet build --configuration $(buildConfiguration) docs/DocsApp/DocsApp.csproj
  displayName: 'dotnet build $(buildConfiguration) DocsApp'
- script: dotnet publish --output $(Build.ArtifactStagingDirectory)/DocsApp docs/DocsApp/DocsApp.csproj
  displayName: 'dotnet publish DocsApp'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'DocsApp'  